### ISSUE TITLE
Exception Handling and seep-common Error package

### ISSUE THREAD

**Issue by pgaref** [raulcf/SEEPng#55]
I was recently looking at the ITuple class code and found some TODOs that need to throw proper exceptions. I was thinking to add some code there but I have two questions: 
- Should all the  custom SEEP exceptions be part of seep-common => uk.ac.imperial.lsds.seep.errors class? Because for example SchemaException is implemented ouside this package.
- Should we have a generic Exception for all the related cases or create more specific ones? For example in the ITuple class we would throw a SchemaException or a fieldName/Type Exception ?

Cheers,
Panagiotis

**Comment by raulcf** [comment]
Hi Panagiotis,

> Should all the custom SEEP exceptions be part 
> of seep-common => uk.ac.imperial.lsds.seep.errors class?

In general yes.

> Because for example SchemaException is implemented ouside this package.

Ah! where is it? It may be a good idea to move it with the rest.

> Should we have a generic Exception for all the related cases or create more 
> specific ones? For example in the ITuple class we would throw a SchemaException
> or a fieldName/Type Exception ?

One point of throwing an exception is to capture the anomaly that happened and report it with (possibly) additional information to the user. Creating too many specific exceptions is bad. Creating a few generic exceptions is bad. It is really a practical issue that depends on on a per-case basis.

> For example in the ITuple class we would throw a SchemaException or a fieldName/Type Exception ?

If we can convey the specific problem with the schema in the text that goes with SchemaException, then I think it's ok. If we think that that more specific exception can be used in any other place, then that's good as well.

Last, it is crucially important to pay attention to the exceptions that already exist in the standard library and use them instead of specific ones when appropriate.

Please, can you attach the ITuple class to this discussion to provide more context? That way it's also easier to look at the particular examples

Thanks!

**Comment by pgaref** [comment]
> >  Because for example SchemaException is implemented ouside this package.
> 
> Ah! where is it? It may be a good idea to move it with the rest.

It is implemented in **uk.ac.imperial.lsds.seep.api.data** package instead of **uk.ac.imperial.lsds.seep.errors**

> Please, can you attach the ITuple class to this discussion to provide more context? That way it's also easier to look at the particular examples

Sure check the code I am talking about below. For this case I would use the SchemaException with a wrong field / wrong type text for each specific type. For example in the getShort method I would use something like: throw new SchemaException("Schema does not have a SHORT field with name "+fieldName );

Let me know if it makes sense.

``` Java
package uk.ac.imperial.lsds.seep.api.data;


public class ITuple {

...

    public short getShort(String fieldName){
        if(! schema.hasField(fieldName)){
            // TODO: error no field
        }
        if(! schema.typeCheck(fieldName, Type.BYTE)) {
            // TODO: does not type check
        }

        int offset = mapFieldToOffset.get(fieldName);
        wrapper.position(offset);
        return wrapper.getShort();
    }

    public int getInt(String fieldName){
        if(! schema.hasField(fieldName)){
            // TODO: error no field
        }
        if(! schema.typeCheck(fieldName, Type.BYTE)) {
            // TODO: does not type check
        }

        int offset = mapFieldToOffset.get(fieldName);
        wrapper.position(offset);
        return wrapper.getInt();
    }

    public long getLong(String fieldName){
        if(! schema.hasField(fieldName)){
            // TODO: error no field
        }
        if(! schema.typeCheck(fieldName, Type.BYTE)) {
            // TODO: does not type check
        }

        int offset = mapFieldToOffset.get(fieldName);
        wrapper.position(offset);
        return wrapper.getLong();
    }

    public String getString(String fieldName){
        if(! schema.hasField(fieldName)){
            // TODO: error no field
        }
        else if(! schema.typeCheck(fieldName, Type.BYTE)) {
            // TODO: does not type check
        }

        int offset = mapFieldToOffset.get(fieldName);
        wrapper.position(offset);
        String str = (String) Type.STRING.read(wrapper);
        return str;
    }

    public Object get(String fieldName){
        if(! schema.hasField(fieldName)){
            // TODO: error no field
        }

...
}
```

**Comment by raulcf** [comment]
> It is implemented in uk.ac.imperial.lsds.seep.api.data 
> package instead of uk.ac.imperial.lsds.seep.errors

Feel free to move it to errors

> For example in the getShort method I would use something 
> like: throw new SchemaException("Schema does not have 
> a SHORT field with name "+fieldName );

That makes a lot of sense.
