### ISSUE TITLE
SchemaParser breaks serialization

### ISSUE THREAD

**Issue by raulcf** [raulcf/SEEPng#63]
SchemaParser contains a Charset attribute that breaks serialization when sent to workers. Non-serializable objects should be created lazily when needed, or through some initialization method when the class is created.

**Comment by WJCIV** [comment]
That's odd. I didn't have any problems. I'll look at it immediately. The fixes that spring to mind are storing the Charset name instead of the Charset itself or just using a default Charset built (and destroyed) on demand.

**Comment by raulcf** [comment]
> The fixes that spring to mind are storing the Charset name instead of the Charset itself

This sounds good.

**Comment by raulcf** [comment]
I think this was fixed, correct?

**Comment by WJCIV** [comment]
Yes.
